name: 'AWS CodeArtifact Next Version'
description: 'Fetch the next sequential version from an AWS CodeArtifact package'
branding:
  icon: 'cloud'
  color: 'green'
inputs:
  domain:
    description: 'The name of the domain that contains the repository that contains the returned package versions (see AWS SDK)'
    required: true
  package:
    description: 'The 12-digit account number of the AWS account that owns the domain (see AWS SDK)'
    required: true
  repository:
    description: 'The name of the repository that contains the package (see AWS SDK)'
    required: true
  format:
    description: 'The format of the returned packages (see AWS SDK)'
    required: false
  prefix:
    description: 'Package version prefix'
    required: false
  die-on-missing:
    description: 'Throw an exception if a package matching the prefix was not found. Otherwise, start a new version'
    required: false
  increment-amount:
    description: 'Amount to increment the version number by'
    required: false
outputs:
  version_number:
    description: 'The incremented version number'
runs:
  using: 'node20'
  main: 'dist/index.js'
